name: MusicRoom42
description: Music Room - 42 Project
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  auto_size_text: ^2.1.0
  build_runner: ^1.11.1
  cloud_firestore: 0.14.0+2
  cupertino_icons: ^0.1.2
  date_time_picker: ^1.1.1
  easy_debounce: ^1.0.2
  firebase_auth: ^0.18.0
  firebase_core: ^0.5.0
  firebase_crashlytics: ^0.2.0
  firebase_database: ^4.0.0
  firebase_performance: "^0.4.2"
  flutter:
    sdk: flutter
  flutter_dotenv: ^3.1.0
  flutter_form_builder: ^4.2.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^0.11.0
  flutter_map_location: # ^0.7.1
    git:
      url: https://github.com/ade-verd/flutter_map_location.git
      ref: v0.7.1_with_initiallyRequest
  flutter_platform_widgets: ^0.32.4
  flutter_slidable: ^0.5.7
  flutter_typeahead: ^1.9.3
  geoflutterfire: ^2.2.1
  location: ^3.2.4
  google_sign_in: ^4.4.6
  json_annotation: ^3.1.1
  latlong: ^0.6.1
  line_icons: ^1.3.2
  logger: ^0.9.4
  maps_launcher: ^1.2.2+2
  marquee: ^1.7.0
  osm_nominatim: ^1.0.1
  pagination_view: ^1.0.4+2
  palette_generator: ^0.2.3
  provider: ^4.0.4
  shared_preferences: ^0.5.6+1
  simple_animations: ^1.3.3
  spotify:
    git:
      url: https://github.com/oozkaya/spotify-dart.git
      ref: master
  spotify_sdk:
    git:
      url: https://github.com/oozkaya/spotify_sdk.git
      ref: 1.0.2
  transparent_image: ^1.0.0
  tuple: ^1.0.3
  uni_links: ^0.4.0
  url_launcher: ^5.7.10
  uuid: ^2.0.4

dev_dependencies:
  dartdoc: ^0.39.0
  dhttpd: ^3.0.2
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.1

flutter_icons:
  adaptive_icon_background: "#FF1DB954"
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/web_hi_res_512.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - lang/
    - assets/images/music_frequencies_green.png
    - assets/images/spotify_loading.gif

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova/Proxima_Nova_Bold.otf
          weight: 500
        - asset: assets/fonts/ProximaNova/Proxima_Nova_Extrabold.otf
          weight: 700
        - asset: assets/fonts/ProximaNova/Proxima_Nova_Black.otf
          weight: 900
        - asset: assets/fonts/ProximaNova/Proxima_Nova_Regular.otf
          style: normal
        - asset: assets/fonts/ProximaNova/Proxima_Nova_Thin.otf
          weight: 100
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans/Product-Sans-Regular.ttf
        - asset: assets/fonts/ProductSans/Product-Sans-Italic.ttf
          style: italic
        - asset: assets/fonts/ProductSans/Product-Sans-Bold.ttf
          weight: 700
